### PR TITLE
PR: Test content-visibility in code mirror css

### PR DESCRIPTION
**Pull request by goanpeca**

### CODE REVIEW

**Comment by goanpeca** [comment]
@echarles made the changes on this branch

https://github.com/goanpeca/jupyterlab/blob/perf-content-visibility/packages/codemirror/style/base.css#L14

And the results..... 🥁 ....

Things look slightly worse.

image


Maybe I need to make the changes elsewhere or wrap in a div?

Thougths?

**Comment by echarles** [comment]
Hi @goanpeca,

I see you have added the `content-visibility` style on the `CodeMirror` class which is embedded in the Shadow DOM. Absolutely not sure if that makes a difference, but to add the style on the `jp-CodeMirrrorEditor` class instead which is out-of-the Shadow DOM tree.  Also, before running on the CI, a first check would be to apply those changes in your local env, build jlab and open a heavy notebook. When you would open/switch that heavy notebook, you should `feel` that it goes faster. Then only when that feeling is observed, you would run on CI to have concrete figures.

Screenshot 2020-09-01 at 05 43 02

**Comment by echarles** [comment]
Without Shadow DOM we have better results (see https://github.com/jupyterlab/benchmarks/pull/33)

**Comment by goanpeca** [comment]
@echarles do you suggest we close this one inn favor of #33 ? or are they complementary somehow?

**Pull request closed without merging**
