### PR TITLE
PR: Install table render as external dependency on dockerfiles using branches

### LINKED ISSUE #61: Add @jupyterlab-benchmarks/table-render in all Dockerfiles and have large output tables
The current Dockerfiles install `@jupyterlab-benchmarks/table-render` on the released version of jupyterlab

https://github.com/jupyterlab/benchmarks/blob/6f6878193c34be3d04385b49db484189e00cf79e/docker/Dockerfile.2-2-8#L5

We also need to have those in the Dockerfiles running in dev mode from the branches.

https://github.com/jupyterlab/benchmarks/blob/6f6878193c34be3d04385b49db484189e00cf79e/docker/Dockerfile.delayout

We also need notebook examples with large output tables to push more the limits

https://github.com/jupyterlab/benchmarks/blob/6f6878193c34be3d04385b49db484189e00cf79e/docker/notebooks/fixedDataTable%20-%20Many%20fixed%20datatable%20outputs%20each%20with%2050%20columns%20and%205000%20rows.ipynb

An notebook with many output table each of 1000 rows could be added.

### PR DESCRIPTION
**Pull request by goanpeca**
Fixes #61

### CODE REVIEW

**Comment by goanpeca** [comment]
@echarles added the changes 

image

Working for delayout and virtual-window

**Comment by goanpeca** [comment]
Not sure if I have access to ru the `make push` 🤷

**Comment by echarles** [comment]
> Not sure if I have access to ru the make push 🤷

You should have access now

**Comment by echarles** [comment]
Thx @goanpeca Overall looks good. On https://github.com/jupyterlab/benchmarks/issues/61#issue-739176680 `We also need notebook examples with large output tables to push more the limits`.

It would be good to create a new notebook with e.g 1000 rows in the output area and see if the browser can display them. The docker image should have that specific notebook that could reside in the root folder aside the `generated-1000cells-0.9ratio-2loc.ipynb` notebook.

**Comment by goanpeca** [comment]
>It would be good to create a new notebook with e.g 1000 rows in the output area and see if the browser can display them. The docker image should have that specific notebook that could reside in the root folder aside the generated-1000cells-0.9ratio-2loc.ipynb notebook.

Working on that.

**Comment by goanpeca** [comment]
@echarles added a notebook with 100 cells, and each one has 200 rows and 50 cols. It takes ~30 seconds to open on my local machine, so I guess that can be used as a valid benchmark.

**Review by echarles — APPROVED** [review]
Thx @goanpeca LGTM. Please merge if you think you are done with this PR.

**Pull request merged**
