### PR TITLE
PR: Update playwrigth, add chromium version benchmark, fix data notebook upload

### LINKED ISSUE #23: Add cpu/mem on which the benchmarks has been run in the csv outtput

### LINKED ISSUE #25: Update playwright to latest version
It seems we can update to 1.3.0 some small code changes are needed. We can then add `browser.version()` to the runs json metadata.

### LINKED ISSUE #27: Add some time wait between samples of a test
I think I have seen mostly increasing numbers when running the tests in a row.

So every time a file opens and closes there is some extra work the browser may be doing (cleanup ...) adding a wait time (a second maybe?), a second or so, may make the results less variable (reduce variance) and more accurately measure the specific actions, instead of accumulating browser work from the previous sample.

### LINKED ISSUE #28: CI to upload the generated notebooks
This has worked one time thx to @goanpeca but does not work anymore.

It would be cool to have that working again so we can try on a local server with the generated notebooks.

### PR DESCRIPTION
**Pull request by goanpeca**
Fixes #28
Fixes #27
Fixes #25
Fixes #23

### CODE REVIEW

**Comment by echarles** [comment]
Thx for this @goanpeca 

FYI data folder is shipped in both `result.zip` and `benchmarks.zip`. I guess the intent was to have a separated `data.zip`, which btw would be better names `notebooks` (maybe you can enroll that chang in this PR also, would need ts code update also for that).

**Comment by goanpeca** [comment]
>FYI data folder is shipped in both result.zip and benchmarks.zip. 

Yes, that is expected since the results are produced in Job1 and I wanted to bundle all files inside a single zip file. HAving to download three separate files seemed a bit cumbersome.

I can change the folder name to `notebooks`, that makes sense :-), but I wanted to have all on `results.zip`

Does this make sense?

**Comment by echarles** [comment]
> Yes, that is expected since the results are produced in Job1 and I wanted to bundle all files(also those from Job2) inside a single zip file. Having to download three separate files seemed a bit cumbersome.

Makes sense

> I will change the folder name to notebooks

Thx.

**Comment by goanpeca** [comment]
image

@echarles now notebooks are uploaded in the notebooks folder.

I think this one is ready 🥳

**Review by echarles — APPROVED** [review]
👍

**Pull request merged**
